# Generated by Django 5.0.3 on 2024-03-09 10:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('www', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='direction',
            old_name='update_at',
            new_name='updated_at',
        ),
        migrations.RenameField(
            model_name='site',
            old_name='update_at',
            new_name='updated_at',
        ),
        migrations.RenameField(
            model_name='sitelog',
            old_name='update_at',
            new_name='updated_at',
        ),
        migrations.RenameField(
            model_name='sitetype',
            old_name='update_at',
            new_name='updated_at',
        ),
    ]
